before:
  hooks:
    - go mod tidy
builds:
  -
    id: "color"
    main: ./server.go
    binary: color
    env:
    - CGO_ENABLED=0
    - GO11MODULE=on
    goarch:
      - amd64
    goos:
      - linux
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
